<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/02/28 03:39:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'Ichikawa#123',
  'name' => 'doctrine',
)),);
