<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/02/28 03:46:53
sfConfig::add(array(
  'mod_jobeet_category_enabled' => true,
  'mod_jobeet_category_view_class' => 'sfPHP',
));
